version: "2"

services:
    php:
        container_name: symfony.app
        build: php7-fpm
        volumes:
            - .${APP_PATH}:/var/www/symfony.dev
    nginx:
        container_name: symfony.web
        build: nginx
        ports:
            - 8080:80
        links:
            - php
        volumes:
            - ./nginx/log/:/var/log/nginx
    mysql:
        container_name: symfony.db
        image: mysql:latest
        volumes:
            - ./mysql/.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}